name: Build & Publish Docker Image

on:
  push:
    branches: [ container-setup ]      # or your default branch
    tags: [ 'v*' ]       # optional: trigger on version tags like v1.2.3

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read            # to checkout code
      packages: write           # to publish package
      id-token: write           # if you use OIDC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./ContainerFile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/app:${{ github.sha }}
          # Optionally add multiple tags:
          # tags: |
          #   ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/app:latest
          #   ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/app:${{ github.sha }}

      - name: Output image reference
        run: echo "Published ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/app:${{ github.sha }}"
